// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.4
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Kafka
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class FaultyOrganisation : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"FaultyOrganisation\",\"namespace\":\"Kafka\",\"fields\":[{\"name" +
				"\":\"id\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"shortName\",\"typ" +
				"e\":[\"string\",\"null\"]},{\"name\":\"ovoNumber\",\"type\":[\"string\",\"null\"]}]}");
		private string _id;
		private string _name;
		private string _shortName;
		private string _ovoNumber;
		public virtual Schema Schema
		{
			get
			{
				return FaultyOrganisation._SCHEMA;
			}
		}
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		public string shortName
		{
			get
			{
				return this._shortName;
			}
			set
			{
				this._shortName = value;
			}
		}
		public string ovoNumber
		{
			get
			{
				return this._ovoNumber;
			}
			set
			{
				this._ovoNumber = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.id;
			case 1: return this.name;
			case 2: return this.shortName;
			case 3: return this.ovoNumber;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.id = (System.String)fieldValue; break;
			case 1: this.name = (System.String)fieldValue; break;
			case 2: this.shortName = (System.String)fieldValue; break;
			case 3: this.ovoNumber = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
